site_name: Optimo
theme: 
  language: ka
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - search.highlight
    # - navigation.indexes
    # - navigation.tracking (სოლოს შექმილი თავიდან)
    
extra:
  version:
    provider: mike
plugins:
    - search
    # - pdf-export:
    #     combined: true
nav:
  - სახლი: index.md
  - მენეჯერის სივრცე:
    - პროდუქტები:
      - პროდუქტები:
        - ცხრილი: bo/products/products.md
        # - ცხრილი_ძველი: bo/products/products copy.md
        - დამატება: bo/products/add_products.md
        - რედაქტირება: bo/products/edit_products.md
        - წაშლა: bo/products/delete_products.md
        # - ფასების სინქრონიზაცია: bo/products/price_synch.md
        - ფასების ცვლილება: bo/products/price_change.md
        # - RS-დან ჩამოტვირთვა: bo/products/rs_import_products.md
        # - პროდუქტების ატვირთვა: bo/products/product_import.md
        # - ექსპორტი სასწორისთვის: bo/products/scales_export.md
        # - ექსელში ექსპორტი: bo/products/excel_export.md
        # - ბარკოდის ბეჭდვა: bo/products/print_barcode.md
      - კატეგორიები:
        - ცხრილი: bo/categories/categories.md
        - დამატება: bo/categories/add_category.md
        - რედაქტირება: bo/categories/edit_category.md
        - წაშლა: bo/categories/delete_category.md
      - გადაზიდვები:
        - ცხრილი: bo/transfer/transfer.md
        - დამატება: bo/transfer/add_transfer.md
        - რედაქტირება: bo/transfer/edit_transfer.md
        - წაშლა: bo/transfer/delete_transfer.md
      - ინვენტარიზაცია:
        - ცხრილი: bo/stocktake/stocktake.md
        - დამატება: bo/stocktake/add_stocktake.md
        - რედაქტირება: bo/stocktake/edit_stocktake.md
        - წაშლა: bo/stocktake/delete_stocktake.md
  - მოლარის სივრცე:
    - სისტემური მოთხოვნები: pos/requirements.md